### ISSUE TITLE
fix:(web)Home Page is not displayed. TypeError: Cannot read properties of null (reading 'name') on Home Page.

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#193]
### Describe your issue

While accessing the home page (URL: http://bebalance.eu-central-1.elasticbeanstalk.com), an "Unexpected Application Error" is encountered. The error message indicates that the application is attempting to read the property name from a null value, causing a TypeError.
Error message:
Unexpected Application Error!
Cannot read properties of null (reading 'name')
TypeError: Cannot read properties of null (reading 'name')
    at s7 (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:253:18892)
    at Rl (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:143:383)
    at s3 (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:159:9824)
    at __ (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:161:11851)
    at fg (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:178:2146)
    at rC (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:174:22215)
    at OA (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:174:21797)
    at Tp (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:174:21549)
    at sg (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:174:18062)
    at Q_ (http://bebalance.eu-central-1.elasticbeanstalk.com/assets/index-DRN_jTbX.js:174:17617)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route. (see screenshot).

### Steps to reproduce

1. Open the URL: http://bebalance.eu-central-1.elasticbeanstalk.com/.
2. The error appears immediately on the home page.

### What was the actual result?

The home page fails to load, displaying an "Unexpected Application Error" 

### What was the expected result?

I expected the home page to load correctly.

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/c37fad64-d9d9-415f-99a6-b17c53175301)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by fshabanov** [comment]
The issue doesn't seem to happen anymore
